web/router.ex
defmodule Tracker.Router do
  use Tracker.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
  end

  scope "/", Tracker do
    pipe_through [:browser, :browser_session]
    get "/", PageController, :index
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    get "/logout", SessionController, :delete
    resources "/users", UserController
  end

  scope "/api/v1", Tracker do
    pipe_through :api
    post "/token", SessionController, :token
  end

  # Other scopes may use custom stacks.
  # scope "/api", Tracker do
  #   pipe_through :api
  # end
end

lib/tracker/endpoint.ex
defmodule Tracker.Endpoint do
  use Phoenix.Endpoint, otp_app: :tracker

  socket "/socket", Tracker.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :tracker, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  plug Plug.Session,
    store: :cookie,
    key: "_tracker_key",
    signing_salt: "U01nPsNz"

  plug Tracker.Router
end

lib/tracker/guardian_serializer.ex
defmodule Tracker.GuardianSerializer do
  @behaviour Guardian.Serializer

  alias Tracker.Repo
  alias Tracker.User

  def for_token(user = %User{}), do: { :ok, "User:#{user.id}" }
  def for_token(_), do: { :error, "Unknown resource type" }

  def from_token("User:" <> id), do: { :ok, Repo.get(User, String.to_integer(id)) }
  def from_token(thing), do: { :error, "Unknown resource type" }
end

lib/tracker/repo.ex
defmodule Tracker.Repo do
  use Ecto.Repo, otp_app: :tracker
end

web/models/user.ex
defmodule Tracker.User do
  use Tracker.Web, :model
  alias Tracker.Repo

  schema "users" do
    field :email, :string
    field :encrypted_password, :string
    field :password, :string, virtual: true

    timestamps
  end

  def authenticate(email, password) do
    case Repo.one(from u in __MODULE__, where: u.email == ^email) do
      %__MODULE__{encrypted_password: encrypted_password} = user ->
        if Comeonin.Pbkdf2.checkpw(password, encrypted_password) do
          { :ok, user }
        else
          { :error, :password_incorrect }
        end
      _ ->
        { :error, :user_not_found }
    end
  end

  def changeset(model, context, params \\ :empty) do
    model
    |> cast(params, required_params(context), optional_params(context))
    |> encrypt_password
    |> unique_constraint(:email)
    |> validate_format(:email, ~r/@/)
  end

  defp required_params(:create), do: ~w(email password)
  defp required_params(_), do: ~w()

  defp optional_params(:update), do: ~w(email password)
  defp optional_params(_), do: ~w()

  defp encrypt_password(changeset) do
    case Ecto.Changeset.fetch_change(changeset, :password) do
      { :ok, password } ->
        changeset
        |> change(encrypted_password: Comeonin.Pbkdf2.hashpwsalt(password))
      :error -> changeset
    end
  end
end

web/controllers/page_controller.ex
defmodule Tracker.PageController do
  use Tracker.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/session_controller.ex
defmodule Tracker.SessionController do
  use Tracker.Web, :controller

  alias Tracker.User

  plug :scrub_params, "user" when action in [:create, :token]

  def new(conn, _params) do
    render(conn, Tracker.SessionView, "new.html")
  end

  def create(conn, %{"user" => %{"email" => email, "password" => password}}) do
    case User.authenticate(email, password) do
      {:ok, user} ->
        conn
        |> Guardian.Plug.sign_in(user, :token)
        |> put_flash(:info, "Logged in.")
        |> redirect(to: user_path(conn, :index))
      {:error, _reason} ->
        conn
        |> put_flash(:info, "Incorrect email or password.")
        |> render("new.html")
    end
  end

  # jQuery.post('/api/v1/token', {"user[email]": "oscarduignan@gmail.com", "user[password]": "test"}, function(data, status, xhr) { console.log(data, status, xhr); }, 'json');
  def token(conn, %{"user" => %{"email" => email, "password" => password}}) do
    case User.authenticate(email, password) do
      {:ok, user} ->
        authenticated_conn = Guardian.Plug.sign_in(conn, user, :token)
        render(authenticated_conn, user: user, token: Guardian.Plug.current_token(authenticated_conn))
      {:error, _} -> conn
    end
  end

  def delete(conn, _params) do
    Guardian.Plug.sign_out(conn)
    |> put_flash(:info, "Logged out.")
    |> redirect(to: "/")
  end
end

web/controllers/user_controller.ex
defmodule Tracker.UserController do
  use Tracker.Web, :controller

  alias Tracker.User
  alias Tracker.SessionController

  plug Guardian.Plug.EnsureAuthenticated, %{ on_failure: { SessionController, :new } } when not action in [:new, :create]

  plug :scrub_params, "user" when action in [:create, :update]

  def index(conn, _params) do
    users = Repo.all(User)
    render(conn, "index.html", users: users)
  end

  def new(conn, _params) do
    changeset = User.changeset(%User{}, :create)
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    changeset = User.changeset(%User{}, :create, user_params)

    case Repo.insert(changeset) do
      {:ok, created_user} ->
        case Guardian.Plug.current_resource(conn) do
          nil ->
            conn
            |> Guardian.Plug.sign_in(created_user, :token)
            |> put_flash(:info, "Account created.")
            |> redirect(to: page_path(conn, :index))
          _ ->
            conn
            |> put_flash(:info, "User created.")
            |> redirect(to: user_path(conn, :index))
        end
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    user = Repo.get!(User, id)
    render(conn, "show.html", user: user)
  end

  def edit(conn, %{"id" => id}) do
    user = Repo.get!(User, id)
    changeset = User.changeset(user, :update)
    render(conn, "edit.html", user: user, changeset: changeset)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Repo.get!(User, id)
    changeset = User.changeset(user, :update, user_params)

    case Repo.update(changeset) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: user_path(conn, :show, user))
      {:error, changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Repo.get!(User, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(user)

    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: user_path(conn, :index))
  end
end

web/views/error_view.ex
defmodule Tracker.ErrorView do
  use Tracker.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Server internal error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Tracker.LayoutView do
  use Tracker.Web, :view
end

web/views/page_view.ex
defmodule Tracker.PageView do
  use Tracker.Web, :view
end

web/views/session_view.ex
defmodule Tracker.SessionView do
  use Tracker.Web, :view

  def render("token.json", %{user: user, token: token}) do
    %{user_id: user.id, token: token}
  end
end

web/views/user_view.ex
defmodule Tracker.UserView do
  use Tracker.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <%= if Guardian.Plug.current_token(@conn) do %>
      <%= tag :meta, name: "channel_token", content: Guardian.Plug.current_token(@conn) %>
    <% end %>

    <title>Hello Phoenix!</title>
    <script src="http://code.jquery.com/jquery-2.1.4.min.js"></script>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container" role="main">
      <div class="header clearfix">
        <ul class="nav nav-pills pull-right">
          <%= if Guardian.Plug.current_resource(@conn) do %>
            <li><%= link(Guardian.Plug.current_resource(@conn).email, to: user_path(@conn, :edit, Guardian.Plug.current_resource(@conn))) %></li>
            <li><%= link("Logout", to: session_path(@conn, :delete)) %></li>
          <% else %>
            <li><%= link("Signup", to: user_path(@conn, :new)) %></li>
            <li><%= link("Login", to: session_path(@conn, :new)) %></li>
          <% end %>
        </ul>
      </div>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <%= @inner %>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2>Welcome to Phoenix!</h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="http://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

web/templates/session/new.html.eex
<h2>Login</h2>

<%= form_for @conn, session_path(@conn, :create), [as: :user], fn f -> %>
  <div class="form-group">
    <label>Email</label>
    <%= text_input f, :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Password</label>
    <%= password_input f, :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Login", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/user/edit.html.eex
<h2>Edit user</h2>

<%= render "form.html", changeset: @changeset,
                        action: user_path(@conn, :update, @user) %>

<%= link "Back", to: user_path(@conn, :index) %>

web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below:</p>
      <ul>
        <%= for {attr, message} <- f.errors do %>
          <li><%= humanize(attr) %> <%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :email, "Email", class: "control-label" %>
    <%= text_input f, :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= label f, :password, "Password", class: "control-label" %>
    <%= password_input f, :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/user/index.html.eex
<h2>Listing users</h2>

<table class="table">
  <thead>
    <tr>
      <th style="width:75%;">Email</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.email %></td>

      <td class="text-right">
        <%= link "Show", to: user_path(@conn, :show, user), class: "btn btn-default btn-xs" %>
        <%= link "Edit", to: user_path(@conn, :edit, user), class: "btn btn-default btn-xs" %>
        <%= link "Delete", to: user_path(@conn, :delete, user), method: :DELETE, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New user", to: user_path(@conn, :new) %>

web/templates/user/new.html.eex
<h2>New user</h2>

<%= render "form.html", changeset: @changeset,
                        action: user_path(@conn, :create) %>

<%= link "Back", to: user_path(@conn, :index) %>

web/templates/user/show.html.eex
<h2>Show user</h2>

<ul>

  <li>
    <strong>Email:</strong>
    <%= @user.email %>
  </li>

  <li>
    <strong>Encrypted password:</strong>
    <%= @user.encrypted_password %>
  </li>

</ul>

<%= link "Edit", to: user_path(@conn, :edit, @user) %>
<%= link "Back", to: user_path(@conn, :index) %>